
get http://localhost:8080/

###
get http://localhost:8080/api/words

###
delete http://localhost:8080/api/words/2

###
post http://localhost:8080/api/words/
content-type: application/json

{ "tag": "animal", "englishWord": "dog", "finnishWord": "koira", "swedishWord": "en hund" }

###
post http://localhost:8080/api/words/
content-type: application/json

{ "tag": null, "englishWord": "cat", "finnishWord": "kissa", "swedishWord": null }
