
get http://localhost:8080/

###
get http://localhost:8080/api/words

###
delete http://localhost:8080/api/words/2

###
post http://localhost:8080/api/words/
content-type: application/json

{ "tag": "animal", "englishWord": "dog", "finnishWord": "koira", "swedishWord": "en hund" }

###
post http://localhost:8080/api/words/
content-type: application/json

{ "tag": null, "englishWord": "cat", "finnishWord": "kissa", "swedishWord": null }

###
post http://localhost:8080/api/words/
content-type: application/json

{ "tag": null, "englishWord": "apple", "finnishWord": "omena", "swedishWord": "äpple", "germanWord": "apfel", "italianWord": "mela" }

###
put http://localhost:8080/api/words/
content-type: application/json

{ "id": 3, "tag": null, "english": "apple", "finnish": "omena", "swedish": "äpple", "german": "testing", "italian": "mela"}

###
get http://localhost:8080/api/tests

###
post http://localhost:8080/api/tests/
content-type: application/json

{ "name": "current_test", "from_language": "english", "to_language": "finnish", "words": [{ "from_word": "dog", "to_word": "koira" }] }